# Generated by Django 4.0.6 on 2022-07-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('request_date', models.DateField()),
                ('reservation_number', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('unit_code', models.CharField(max_length=100)),
                ('va_code', models.CharField(max_length=100)),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sales')),
            ],
        ),
    ]
