# Generated by Django 4.0.6 on 2022-07-20 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='amount',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='request_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='reservation_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sales'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='transaction_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='unit_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='va_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
