# Generated by Django 4.0.6 on 2022-07-20 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reserve_amount_alter_reserve_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='request_date',
            field=models.DateField(default=datetime.date(2022, 7, 20), null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='transaction_date',
            field=models.DateField(default=datetime.date(2022, 7, 20), null=True),
        ),
    ]
