# Generated by Django 4.0.6 on 2022-07-25 03:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_reserve_request_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='project',
            field=models.ForeignKey(default='ASG-000003', on_delete=django.db.models.deletion.CASCADE, to='app.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='request_date',
            field=models.DateField(default=datetime.date(2022, 7, 25), null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='transaction_date',
            field=models.DateField(default=datetime.date(2022, 7, 25), null=True),
        ),
    ]
